spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/studentsystem
    driver-class-name: com.mysql.jdbc.Driver
#   数据源其他配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
#   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500





  #禁用thymeleaf缓存
  thymeleaf:
    cache: false

#mybatis映射配置
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml

